version: '1'
services:
  restaurant_db:
    image: postgres:14.1
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
  restaurant:
    container_name: restaurant
    image: restaurant
    restart: unless-stopped
    command: ["java","-jar","restaurant.jar"]
    build: restaurant
    env_file:
      - ../.env
    ports:
      - '${REST_PORT}:${REST_PORT}'
    depends_on:
      - restaurant_db
      - kitchen
      - delivery
  kitchen:
    container_name: kitchen
    image: kitchen
    restart: unless-stopped
    command: ["java","-jar","kitchen.jar"]
    build: kitchen
    env_file:
      - ../.env
    ports:
      - '${KITCH_PORT}:${KITCH_PORT}'
  delivery:
    container_name: delivery
    image: delivery
    restart: unless-stopped
    command: ["java","-jar","delivery.jar"]
    build: delivery
    env_file:
      - ../.env
    ports:
      - '${DELIV_PORT}:${DELIV_PORT}'
